version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cinematch-db
    environment:
      POSTGRES_USER: cinematch
      POSTGRES_PASSWORD: cinematch
      POSTGRES_DB: cinematch
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cinematch-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinematch.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  dbdata:
